### ISSUE TITLE
Missing suggestion for e.g./i.e.

### ISSUE THREAD

**Issue by tezlm** [Automattic/harper#183]
The text:

```
Some text here (eg. more text).
```

Results in these two lints:

- Did you mean to spell "eg" this way?
- This sentence does not start with a capital letter. (in word "more")

Initially, I thought that this was an issue with Harper, but both warnings disappear if I use `e.g.` instead of `eg.`. This (along with `i.e.`) should probably be added to the suggestions list.

**Comment by elijah-potter** [comment]
Thanks for bringing this to my attention. Are you suggesting that, when Harper sees something like `eg.`, it should suggest changing it to `e.g.`?

**Comment by tezlm** [comment]
Yes

**Comment by elijah-potter** [comment]
Sounds good. Since this is relatively simple, I might be able to knock this out sometime tomorrow.

**Comment by elijah-potter** [comment]
This is implemented as of 5357cb3d05003e13845ed69c4d80ef011c95bc2f. I'm going to keep the issue open so you may test it once it's in a release.

**Comment by elijah-potter** [comment]
It looks like this change has finally been picked up by [Mason](https://github.com/mason-org/mason-registry/pull/7536#issuecomment-2507315875). Would you mind confirming it works for you?

**Comment by tezlm** [comment]
I don't use mason, but it looks like it works when compiled from source
