### ISSUE TITLE
feat: Can grammatical tense be detected?

### ISSUE THREAD

**Issue by openapphub** [Automattic/harper#313]
Example：
```
Last Sunday | get up very late. 
```

get -> got

**Comment by elijah-potter** [comment]
It sure can. We've just got it working, but haven't yet had a chance to expose it as a rule. Hang tight and I'll let you know when we've got it in a release!

**Comment by openapphub** [comment]
> It sure can. We've just got it working, but haven't yet had a chance to expose it as a rule. Hang tight and I'll let you know when we've got it in a release!

You're great.
