### ISSUE TITLE
[Bug, harper.js] Unable to Install harper.js with npm

### ISSUE THREAD

**Issue by JackPlowman** [Automattic/harper#339]
# Description 

Hi, I've tried installing harper.js using NPM and it errors with the error listed below.

## Error

```bash
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "link:": link:../../harper-wasm/pkg
```

## Steps to replicate:

To replicate create an empty folder, set up an empty npm package then install harper.js

```bash
mkdir empty
npm init
npm i harper.js
```

## Versions:

MacOS 15.2
npm 10.9.2

## Possible Fix:

I'm not a JS/TS wizard so this may be wrong.

I think that replacing the link with file would fix this issue.

Lines -> https://github.com/Automattic/harper/blob/ace693c00fe7128919c545ffbd22ec0b176b2fcc/packages/harper.js/package.json#L10C1-L12C3

```json
	"dependencies": {
		"wasm": "file:../../harper-wasm/pkg"
	},
```

Related Documentation - Local file linking in package.json -> https://docs.npmjs.com/cli/v9/configuring-npm/package-json#local-paths

Feel free to let me know if I'm doing something dumb

**Comment by elijah-potter** [comment]
Hey @JackPlowman,

Thanks for noticing this. The actual issue is that the `wasm` dependency is actually supposed to be a development dependency. I'll push up a fix in a jiffy. Thanks for giving it go!

I'll toss an update here once that's done.

**Comment by elijah-potter** [comment]
Alright. I believe it should should be working properly now. [We've also got some documentation up](https://writewithharper.com/docs/harperjs/introduction) which we'll be adding to over the next several days.

Give it a whirl and let me know if the issue has been fixed.

**Comment by JackPlowman** [comment]
Just tried it and it can install harper.js. Thanks @elijah-potter
