### ISSUE TITLE
feat: option to change order of code actions

### ISSUE THREAD

**Issue by eamonburns** [Automattic/harper#89]
Currently, the LSP provides code actions like this:

`coole`
```
Code actions:
1. Replace with: "cooled"
2. Replace with: "woolen"
3. Replace with: "cool"
4. Add "coole" to the global dictionary.
5. Add "coole" to the file dictionary.
```

This means that depending on the number of auto-correct suggestions, the `Add to dictionary` actions will be in different spots. This is kind of annoying, because now I have to do a little extra thinking to look at the number corresponding to the action I want, and then pressing it. It would be nice to have the `Add to dictionary` actions be first in the list, so that I know I can always press `1` to add to the global dictionary, `2` to add to the file dictionary, `3` to select the first auto-correct suggestion, and so on.

I know that this might be weird for some people, so it would definitely be best as an optional setting.

**Comment by elijah-potter** [comment]
Sorry it took so long for me to respond to this. I've added a config option to `harper-ls` to do what you describe: `forceStable`. An example config for Neovim using `lspconfig`:

```lua
lspconfig.harper_ls.setup {
  settings = {
    ["harper-ls"] = {
      codeActions = {
        forceStable = true
      }
    }
  },
}
```

This will instruct `harper-ls` to place consistent code actions (that aren't dependent on specific words or anything like that) to the top, in "stable" positions.

I don't plan on doing another release within the next week or so, which means if you want this ASAP, you'll have to build from source. Let me know if you have any other issues!

**Comment by Agent-E11** [comment]
@elijah-potter Thank you very much, it works great! Is this the usual way of installing the bleeding-edge version?:
```sh
cargo install --git https://github.com/elijah-potter/harper harper-ls --locked
```
Because that is what I did

**Comment by elijah-potter** [comment]
That looks right to me. I should add that somewhere in the README...
